language: node_js
node_js:
  - "6.1"
before_install:
 - sudo pip install codecov
 - sudo hostname "$(hostname | cut -c1-63)" # https://github.com/travis-ci/travis-ci/issues/5227
 - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts # https://github.com/travis-ci/travis-ci/issues/5227
after_success:
 - codecov
