/*
 * Copyright (c) 2016, Hugo Freire <hugo@exec.sh>.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports.POKEDEX = [
  {
    "id":"1",
    "num":"001",
    "name":"Bulbasaur",
    "img":"https://pokegorealtime.com/static/images/pokedex/001.png",
    "type": "Grass / Poison",
    "height": "0.71 m",
    "weight": "6.9 kg",
    "candy": "25 Bulbasaur Candy",
    "egg": "2 km"
  },
  {
    "id":"2",
    "num":"002",
    "name":"Ivysaur",
    "img":"https://pokegorealtime.com/static/images/pokedex/002.png",
    "type": "Grass / Poison",
    "height": "0.99 m",
    "weight": "13.0 kg",
    "candy": "100 Bulbasaur Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"3",
    "num":"003",
    "name":"Venusaur",
    "img":"https://pokegorealtime.com/static/images/pokedex/003.png",
    "type": "Grass / Poison",
    "height": "2.01 m",
    "weight": "100.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"4",
    "num":"004",
    "name":"Charmander",
    "img":"https://pokegorealtime.com/static/images/pokedex/004.png",
    "type": "Fire",
    "height": "0.61 m",
    "weight": "8.5 kg",
    "candy": "25 Charmander Candy",
    "egg": "2 km"
  },
  {
    "id":"5",
    "num":"005",
    "name":"Charmeleon",
    "img":"https://pokegorealtime.com/static/images/pokedex/005.png",
    "type": "Fire",
    "height": "1.09 m",
    "weight": "19.0 kg",
    "candy": "100 Charmander Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"6",
    "num":"006",
    "name":"Charizard",
    "img":"https://pokegorealtime.com/static/images/pokedex/006.png",
    "type": "Fire / Flying",
    "height": "1.70 m",
    "weight": "90.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"7",
    "num":"007",
    "name":"Squirtle",
    "img":"https://pokegorealtime.com/static/images/pokedex/007.png",
    "type": "Water",
    "height": "0.51 m",
    "weight": "9.0 kg",
    "candy": "25 Squirtle Candy",
    "egg": "2 km"
  },
  {
    "id":"8",
    "num":"008",
    "name":"Wartortle",
    "img":"https://pokegorealtime.com/static/images/pokedex/008.png",
    "type": "Water",
    "height": "0.99 m",
    "weight": "22.5 kg",
    "candy": "100 Squirtle Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"9",
    "num":"009",
    "name":"Blastoise",
    "img":"https://pokegorealtime.com/static/images/pokedex/009.png",
    "type": "Water",
    "height": "1.60 m",
    "weight": "85.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"10",
    "num":"010",
    "name":"Caterpie",
    "img":"https://pokegorealtime.com/static/images/pokedex/010.png",
    "type": "Bug",
    "height": "0.30 m",
    "weight": "2.9 kg",
    "candy": "12 Caterpie Candy",
    "egg": "2 km"
  },
  {
    "id":"11",
    "num":"011",
    "name":"Metapod",
    "img":"https://pokegorealtime.com/static/images/pokedex/011.png",
    "type": "Bug",
    "height": "0.71 m",
    "weight": "9.9 kg",
    "candy": "50 Caterpie Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"12",
    "num":"012",
    "name":"Butterfree",
    "img":"https://pokegorealtime.com/static/images/pokedex/012.png",
    "type": "Bug / Flying",
    "height": "1.09 m",
    "weight": "32.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"13",
    "num":"013",
    "name":"Weedle",
    "img":"https://pokegorealtime.com/static/images/pokedex/013.png",
    "type": "Bug / Poison",
    "height": "0.30 m",
    "weight": "3.2 kg",
    "candy": "12 Weedle Candy",
    "egg": "2 km"
  },
  {
    "id":"14",
    "num":"014",
    "name":"Kakuna",
    "img":"https://pokegorealtime.com/static/images/pokedex/014.png",
    "type": "Bug / Poison",
    "height": "0.61 m",
    "weight": "10.0 kg",
    "candy": "50 Weedle Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"15",
    "num":"015",
    "name":"Beedrill",
    "img":"https://pokegorealtime.com/static/images/pokedex/015.png",
    "type": "Bug / Poison",
    "height": "0.99 m",
    "weight": "29.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"16",
    "num":"016",
    "name":"Pidgey",
    "img":"https://pokegorealtime.com/static/images/pokedex/016.png",
    "type": "Normal / Flying",
    "height": "0.30 m",
    "weight": "1.8 kg",
    "candy": "12 Pidgey Candy",
    "egg": "2 km"
  },
  {
    "id":"17",
    "num":"017",
    "name":"Pidgeotto",
    "img":"https://pokegorealtime.com/static/images/pokedex/017.png",
    "type": "Normal / Flying",
    "height": "1.09 m",
    "weight": "30.0 kg",
    "candy": "50 Pidgey Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"18",
    "num":"018",
    "name":"Pidgeot",
    "img":"https://pokegorealtime.com/static/images/pokedex/018.png",
    "type": "Normal / Flying",
    "height": "1.50 m",
    "weight": "39.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"19",
    "num":"019",
    "name":"Rattata",
    "img":"https://pokegorealtime.com/static/images/pokedex/019.png",
    "type": "Normal",
    "height": "0.30 m",
    "weight": "3.5 kg",
    "candy": "25 Rattata Candy",
    "egg": "2 km"
  },
  {
    "id":"20",
    "num":"020",
    "name":"Raticate",
    "img":"https://pokegorealtime.com/static/images/pokedex/020.png",
    "type": "Normal",
    "height": "0.71 m",
    "weight": "18.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"21",
    "num":"021",
    "name":"Spearow",
    "img":"https://pokegorealtime.com/static/images/pokedex/021.png",
    "type": "Normal / Flying",
    "height": "0.30 m",
    "weight": "2.0 kg",
    "candy": "50 Spearow Candy",
    "egg": "2 km"
  },
  {
    "id":"22",
    "num":"022",
    "name":"Fearow",
    "img":"https://pokegorealtime.com/static/images/pokedex/022.png",
    "type": "Normal / Flying",
    "height": "1.19 m",
    "weight": "38.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"23",
    "num":"023",
    "name":"Ekans",
    "img":"https://pokegorealtime.com/static/images/pokedex/023.png",
    "type": "Poison",
    "height": "2.01 m",
    "weight": "6.9 kg",
    "candy": "50 Ekans Candy",
    "egg": "5 km"
  },
  {
    "id":"24",
    "num":"024",
    "name":"Arbok",
    "img":"https://pokegorealtime.com/static/images/pokedex/024.png",
    "type": "Poison",
    "height": "3.51 m",
    "weight": "65.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"25",
    "num":"025",
    "name":"Pikachu",
    "img":"https://pokegorealtime.com/static/images/pokedex/025.png",
    "type": "Electric",
    "height": "0.41 m",
    "weight": "6.0 kg",
    "candy": "50 Pikachu Candy",
    "egg": "2 km"
  },
  {
    "id":"26",
    "num":"026",
    "name":"Raichu",
    "img":"https://pokegorealtime.com/static/images/pokedex/026.png",
    "type": "Electric",
    "height": "0.79 m",
    "weight": "30.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"27",
    "num":"027",
    "name":"Sandshrew",
    "img":"https://pokegorealtime.com/static/images/pokedex/027.png",
    "type": "Ground",
    "height": "0.61 m",
    "weight": "12.0 kg",
    "candy": "50 Sandshrew Candy",
    "egg": "5 km"
  },
  {
    "id":"28",
    "num":"028",
    "name":"Sandslash",
    "img":"https://pokegorealtime.com/static/images/pokedex/028.png",
    "type": "Ground",
    "height": "0.99 m",
    "weight": "29.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"29",
    "num":"029",
    "name":"Nidoran ♀",
    "img":"https://pokegorealtime.com/static/images/pokedex/029.png",
    "type": "Poison",
    "height": "0.41 m",
    "weight": "7.0 kg",
    "candy": "25 Nidoran ♀ Candy",
    "egg": "5 km"
  },
  {
    "id":"30",
    "num":"030",
    "name":"Nidorina",
    "img":"https://pokegorealtime.com/static/images/pokedex/030.png",
    "type": "Poison",
    "height": "0.79 m",
    "weight": "20.0 kg",
    "candy": "100 Nidoran ♀ Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"31",
    "num":"031",
    "name":"Nidoqueen",
    "img":"https://pokegorealtime.com/static/images/pokedex/031.png",
    "type": "Poison / Ground",
    "height": "1.30 m",
    "weight": "60.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"32",
    "num":"032",
    "name":"Nidoran ♂",
    "img":"https://pokegorealtime.com/static/images/pokedex/032.png",
    "type": "Poison",
    "height": "0.51 m",
    "weight": "9.0 kg",
    "candy": "25 Nidoran♂ Candy",
    "egg": "5 km"
  },
  {
    "id":"33",
    "num":"033",
    "name":"Nidorino",
    "img":"https://pokegorealtime.com/static/images/pokedex/033.png",
    "type": "Poison",
    "height": "0.89 m",
    "weight": "19.5 kg",
    "candy": "100 Nidoran ♂ Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"34",
    "num":"034",
    "name":"Nidoking",
    "img":"https://pokegorealtime.com/static/images/pokedex/034.png",
    "type": "Poison / Ground",
    "height": "1.40 m",
    "weight": "62.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"35",
    "num":"035",
    "name":"Clefairy",
    "img":"https://pokegorealtime.com/static/images/pokedex/035.png",
    "type": "Normal",
    "height": "0.61 m",
    "weight": "7.5 kg",
    "candy": "50 Clefairy Candy",
    "egg": "2 km"
  },
  {
    "id":"36",
    "num":"036",
    "name":"Clefable",
    "img":"https://pokegorealtime.com/static/images/pokedex/036.png",
    "type": "Normal",
    "height": "1.30 m",
    "weight": "40.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"37",
    "num":"037",
    "name":"Vulpix",
    "img":"https://pokegorealtime.com/static/images/pokedex/037.png",
    "type": "Fire",
    "height": "0.61 m",
    "weight": "9.9 kg",
    "candy": "50 Vulpix Candy",
    "egg": "5 km"
  },
  {
    "id":"38",
    "num":"038",
    "name":"Ninetales",
    "img":"https://pokegorealtime.com/static/images/pokedex/038.png",
    "type": "Fire",
    "height": "1.09 m",
    "weight": "19.9 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"39",
    "num":"039",
    "name":"Jigglypuff",
    "img":"https://pokegorealtime.com/static/images/pokedex/039.png",
    "type": "Normal",
    "height": "0.51 m",
    "weight": "5.5 kg",
    "candy": "50 Jigglypuff Candy",
    "egg": "2 km"
  },
  {
    "id":"40",
    "num":"040",
    "name":"Wigglytuff",
    "img":"https://pokegorealtime.com/static/images/pokedex/040.png",
    "type": "Normal",
    "height": "0.99 m",
    "weight": "12.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"41",
    "num":"041",
    "name":"Zubat",
    "img":"https://pokegorealtime.com/static/images/pokedex/041.png",
    "type": "Poison / Flying",
    "height": "0.79 m",
    "weight": "7.5 kg",
    "candy": "50 Zubat Candy",
    "egg": "2 km"
  },
  {
    "id":"42",
    "num":"042",
    "name":"Golbat",
    "img":"https://pokegorealtime.com/static/images/pokedex/042.png",
    "type": "Poison / Flying",
    "height": "1.60 m",
    "weight": "55.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"43",
    "num":"043",
    "name":"Oddish",
    "img":"https://pokegorealtime.com/static/images/pokedex/043.png",
    "type": "Grass / Poison",
    "height": "0.51 m",
    "weight": "5.4 kg",
    "candy": "25 Oddish Candy",
    "egg": "5 km"
  },
  {
    "id":"44",
    "num":"044",
    "name":"Gloom",
    "img":"https://pokegorealtime.com/static/images/pokedex/044.png",
    "type": "Grass / Poison",
    "height": "0.79 m",
    "weight": "8.6 kg",
    "candy": "100 Oddish Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"45",
    "num":"045",
    "name":"Vileplume",
    "img":"https://pokegorealtime.com/static/images/pokedex/045.png",
    "type": "Grass / Poison",
    "height": "1.19 m",
    "weight": "18.6 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"46",
    "num":"046",
    "name":"Paras",
    "img":"https://pokegorealtime.com/static/images/pokedex/046.png",
    "type": "Bug / Grass",
    "height": "0.30 m",
    "weight": "5.4 kg",
    "candy": "50 Paras Candy",
    "egg": "5 km"
  },
  {
    "id":"47",
    "num":"047",
    "name":"Parasect",
    "img":"https://pokegorealtime.com/static/images/pokedex/047.png",
    "type": "Bug / Grass",
    "height": "0.99 m",
    "weight": "29.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"48",
    "num":"048",
    "name":"Venonat",
    "img":"https://pokegorealtime.com/static/images/pokedex/048.png",
    "type": "Bug / Poison",
    "height": "0.99 m",
    "weight": "30.0 kg",
    "candy": "50 Venonat Candy",
    "egg": "5 km"
  },
  {
    "id":"49",
    "num":"049",
    "name":"Venomoth",
    "img":"https://pokegorealtime.com/static/images/pokedex/049.png",
    "type": "Bug / Poison",
    "height": "1.50 m",
    "weight": "12.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"50",
    "num":"050",
    "name":"Diglett",
    "img":"https://pokegorealtime.com/static/images/pokedex/050.png",
    "type": "Ground",
    "height": "0.20 m",
    "weight": "0.8 kg",
    "candy": "50 Diglett Candy",
    "egg": "5 km"
  },
  {
    "id":"51",
    "num":"051",
    "name":"Dugtrio",
    "img":"https://pokegorealtime.com/static/images/pokedex/051.png",
    "type": "Ground",
    "height": "0.71 m",
    "weight": "33.3 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"52",
    "num":"052",
    "name":"Meowth",
    "img":"https://pokegorealtime.com/static/images/pokedex/052.png",
    "type": "Normal",
    "height": "0.41 m",
    "weight": "4.2 kg",
    "candy": "50 Meowth Candy",
    "egg": "5 km"
  },
  {
    "id":"53",
    "num":"053",
    "name":"Persian",
    "img":"https://pokegorealtime.com/static/images/pokedex/053.png",
    "type": "Normal",
    "height": "0.99 m",
    "weight": "32.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"54",
    "num":"054",
    "name":"Psyduck",
    "img":"https://pokegorealtime.com/static/images/pokedex/054.png",
    "type": "Water",
    "height": "0.79 m",
    "weight": "19.6 kg",
    "candy": "50 Psyduck Candy",
    "egg": "5 km"
  },
  {
    "id":"55",
    "num":"055",
    "name":"Golduck",
    "img":"https://pokegorealtime.com/static/images/pokedex/055.png",
    "type": "Water",
    "height": "1.70 m",
    "weight": "76.6 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"56",
    "num":"056",
    "name":"Mankey",
    "img":"https://pokegorealtime.com/static/images/pokedex/056.png",
    "type": "Fighting",
    "height": "0.51 m",
    "weight": "28.0 kg",
    "candy": "50 Mankey Candy",
    "egg": "5 km"
  },
  {
    "id":"57",
    "num":"057",
    "name":"Primeape",
    "img":"https://pokegorealtime.com/static/images/pokedex/057.png",
    "type": "Fighting",
    "height": "0.99 m",
    "weight": "32.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"58",
    "num":"058",
    "name":"Growlithe",
    "img":"https://pokegorealtime.com/static/images/pokedex/058.png",
    "type": "Fire",
    "height": "0.71 m",
    "weight": "19.0 kg",
    "candy": "50 Growlithe Candy",
    "egg": "5 km"
  },
  {
    "id":"59",
    "num":"059",
    "name":"Arcanine",
    "img":"https://pokegorealtime.com/static/images/pokedex/059.png",
    "type": "Fire",
    "height": "1.91 m",
    "weight": "155.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"60",
    "num":"060",
    "name":"Poliwag",
    "img":"https://pokegorealtime.com/static/images/pokedex/060.png",
    "type": "Water",
    "height": "0.61 m",
    "weight": "12.4 kg",
    "candy": "25 Poliwag Candy",
    "egg": "5 km"
  },
  {
    "id":"61",
    "num":"061",
    "name":"Poliwhirl",
    "img":"https://pokegorealtime.com/static/images/pokedex/061.png",
    "type": "Water",
    "height": "0.99 m",
    "weight": "20.0 kg",
    "candy": "100 Poliwag Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"62",
    "num":"062",
    "name":"Poliwrath",
    "img":"https://pokegorealtime.com/static/images/pokedex/062.png",
    "type": "Water / Fighting",
    "height": "1.30 m",
    "weight": "54.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"63",
    "num":"063",
    "name":"Abra",
    "img":"https://pokegorealtime.com/static/images/pokedex/063.png",
    "type": "Psychic",
    "height": "0.89 m",
    "weight": "19.5 kg",
    "candy": "25 Abra Candy",
    "egg": "5 km"
  },
  {
    "id":"64",
    "num":"064",
    "name":"Kadabra",
    "img":"https://pokegorealtime.com/static/images/pokedex/064.png",
    "type": "Psychic",
    "height": "1.30 m",
    "weight": "56.5 kg",
    "candy": "100 Abra Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"65",
    "num":"065",
    "name":"Alakazam",
    "img":"https://pokegorealtime.com/static/images/pokedex/065.png",
    "type": "Psychic",
    "height": "1.50 m",
    "weight": "48.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"66",
    "num":"066",
    "name":"Machop",
    "img":"https://pokegorealtime.com/static/images/pokedex/066.png",
    "type": "Fighting",
    "height": "0.79 m",
    "weight": "19.5 kg",
    "candy": "25 Machop Candy",
    "egg": "5 km"
  },
  {
    "id":"67",
    "num":"067",
    "name":"Machoke",
    "img":"https://pokegorealtime.com/static/images/pokedex/067.png",
    "type": "Fighting",
    "height": "1.50 m",
    "weight": "70.5 kg",
    "candy": "100 Machop Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"68",
    "num":"068",
    "name":"Machamp",
    "img":"https://pokegorealtime.com/static/images/pokedex/068.png",
    "type": "Fighting",
    "height": "1.60 m",
    "weight": "130.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"69",
    "num":"069",
    "name":"Bellsprout",
    "img":"https://pokegorealtime.com/static/images/pokedex/069.png",
    "type": "Grass / Poison",
    "height": "0.71 m",
    "weight": "4.0 kg",
    "candy": "25 Bellsprout Candy",
    "egg": "5 km"
  },
  {
    "id":"70",
    "num":"070",
    "name":"Weepinbell",
    "img":"https://pokegorealtime.com/static/images/pokedex/070.png",
    "type": "Grass / Poison",
    "height": "0.99 m",
    "weight": "6.4 kg",
    "candy": "100 Bellsprout Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"71",
    "num":"071",
    "name":"Victreebel",
    "img":"https://pokegorealtime.com/static/images/pokedex/071.png",
    "type": "Grass / Poison",
    "height": "1.70 m",
    "weight": "15.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"72",
    "num":"072",
    "name":"Tentacool",
    "img":"https://pokegorealtime.com/static/images/pokedex/072.png",
    "type": "Water / Poison",
    "height": "0.89 m",
    "weight": "45.5 kg",
    "candy": "50 Tentacool Candy",
    "egg": "5 km"
  },
  {
    "id":"73",
    "num":"073",
    "name":"Tentacruel",
    "img":"https://pokegorealtime.com/static/images/pokedex/073.png",
    "type": "Water / Poison",
    "height": "1.60 m",
    "weight": "55.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"74",
    "num":"074",
    "name":"Geodude",
    "img":"https://pokegorealtime.com/static/images/pokedex/074.png",
    "type": "Rock / Ground",
    "height": "0.41 m",
    "weight": "20.0 kg",
    "candy": "25 Geodude Candy",
    "egg": "2 km"
  },
  {
    "id":"75",
    "num":"075",
    "name":"Graveler",
    "img":"https://pokegorealtime.com/static/images/pokedex/075.png",
    "type": "Rock / Ground",
    "height": "0.99 m",
    "weight": "105.0 kg",
    "candy": "100 Geodude Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"76",
    "num":"076",
    "name":"Golem",
    "img":"https://pokegorealtime.com/static/images/pokedex/076.png",
    "type": "Rock / Ground",
    "height": "1.40 m",
    "weight": "300.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"77",
    "num":"077",
    "name":"Ponyta",
    "img":"https://pokegorealtime.com/static/images/pokedex/077.png",
    "type": "Fire",
    "height": "0.99 m",
    "weight": "30.0 kg",
    "candy": "50 Ponyta Candy",
    "egg": "5 km"
  },
  {
    "id":"78",
    "num":"078",
    "name":"Rapidash",
    "img":"https://pokegorealtime.com/static/images/pokedex/078.png",
    "type": "Fire",
    "height": "1.70 m",
    "weight": "95.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"79",
    "num":"079",
    "name":"Slowpoke",
    "img":"https://pokegorealtime.com/static/images/pokedex/079.png",
    "type": "Water / Psychic",
    "height": "1.19 m",
    "weight": "36.0 kg",
    "candy": "50 Slowpoke Candy",
    "egg": "5 km"
  },
  {
    "id":"80",
    "num":"080",
    "name":"Slowbro",
    "img":"https://pokegorealtime.com/static/images/pokedex/080.png",
    "type": "Water / Psychic",
    "height": "1.60 m",
    "weight": "78.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"81",
    "num":"081",
    "name":"Magnemite",
    "img":"https://pokegorealtime.com/static/images/pokedex/081.png",
    "type": "Electric",
    "height": "0.30 m",
    "weight": "6.0 kg",
    "candy": "50 Magnemite Candy",
    "egg": "5 km"
  },
  {
    "id":"82",
    "num":"082",
    "name":"Magneton",
    "img":"https://pokegorealtime.com/static/images/pokedex/082.png",
    "type": "Electric",
    "height": "0.99 m",
    "weight": "60.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"83",
    "num":"083",
    "name":"Farfetch'd",
    "img":"https://pokegorealtime.com/static/images/pokedex/083.png",
    "type": "Normal / Flying",
    "height": "0.79 m",
    "weight": "15.0 kg",
    "candy": "None",
    "egg": "5 km"
  },
  {
    "id":"84",
    "num":"084",
    "name":"Doduo",
    "img":"https://pokegorealtime.com/static/images/pokedex/084.png",
    "type": "Normal / Flying",
    "height": "1.40 m",
    "weight": "39.2 kg",
    "candy": "50 Doduo Candy",
    "egg": "5 km"
  },
  {
    "id":"85",
    "num":"085",
    "name":"Dodrio",
    "img":"https://pokegorealtime.com/static/images/pokedex/085.png",
    "type": "Normal / Flying",
    "height": "1.80 m",
    "weight": "85.2 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"86",
    "num":"086",
    "name":"Seel",
    "img":"https://pokegorealtime.com/static/images/pokedex/086.png",
    "type": "Water",
    "height": "1.09 m",
    "weight": "90.0 kg",
    "candy": "50 Seel Candy",
    "egg": "5 km"
  },
  {
    "id":"87",
    "num":"087",
    "name":"Dewgong",
    "img":"https://pokegorealtime.com/static/images/pokedex/087.png",
    "type": "Water / Ice",
    "height": "1.70 m",
    "weight": "120.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"88",
    "num":"088",
    "name":"Grimer",
    "img":"https://pokegorealtime.com/static/images/pokedex/088.png",
    "type": "Poison",
    "height": "0.89 m",
    "weight": "30.0 kg",
    "candy": "50 Grimer Candy",
    "egg": "5 km"
  },
  {
    "id":"89",
    "num":"089",
    "name":"Muk",
    "img":"https://pokegorealtime.com/static/images/pokedex/089.png",
    "type": "Poison",
    "height": "1.19 m",
    "weight": "30.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"90",
    "num":"090",
    "name":"Shellder",
    "img":"https://pokegorealtime.com/static/images/pokedex/090.png",
    "type": "Water",
    "height": "0.30 m",
    "weight": "4.0 kg",
    "candy": "50 Shellder Candy",
    "egg": "5 km"
  },
  {
    "id":"91",
    "num":"091",
    "name":"Cloyster",
    "img":"https://pokegorealtime.com/static/images/pokedex/091.png",
    "type": "Water / Ice",
    "height": "1.50 m",
    "weight": "132.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"92",
    "num":"092",
    "name":"Gastly",
    "img":"https://pokegorealtime.com/static/images/pokedex/092.png",
    "type": "Ghost / Poison",
    "height": "1.30 m",
    "weight": "0.1 kg",
    "candy": "25 Gastly Candy",
    "egg": "5 km"
  },
  {
    "id":"93",
    "num":"093",
    "name":"Haunter",
    "img":"https://pokegorealtime.com/static/images/pokedex/093.png",
    "type": "Ghost / Poison",
    "height": "1.60 m",
    "weight": "0.1 kg",
    "candy": "100 Gastly Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"94",
    "num":"094",
    "name":"Gengar",
    "img":"https://pokegorealtime.com/static/images/pokedex/094.png",
    "type": "Ghost / Poison",
    "height": "1.50 m",
    "weight": "40.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"95",
    "num":"095",
    "name":"Onix",
    "img":"https://pokegorealtime.com/static/images/pokedex/095.png",
    "type": "Rock / Ground",
    "height": "8.79 m",
    "weight": "210.0 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"96",
    "num":"096",
    "name":"Drowzee",
    "img":"https://pokegorealtime.com/static/images/pokedex/096.png",
    "type": "Psychic",
    "height": "0.99 m",
    "weight": "32.4 kg",
    "candy": "50 Drowzee Candy",
    "egg": "5 km"
  },
  {
    "id":"97",
    "num":"097",
    "name":"Hypno",
    "img":"https://pokegorealtime.com/static/images/pokedex/097.png",
    "type": "Psychic",
    "height": "1.60 m",
    "weight": "75.6 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"98",
    "num":"098",
    "name":"Krabby",
    "img":"https://pokegorealtime.com/static/images/pokedex/098.png",
    "type": "Water",
    "height": "0.41 m",
    "weight": "6.5 kg",
    "candy": "50 Krabby Candy",
    "egg": "5 km"
  },
  {
    "id":"99",
    "num":"099",
    "name":"Kingler",
    "img":"https://pokegorealtime.com/static/images/pokedex/099.png",
    "type": "Water",
    "height": "1.30 m",
    "weight": "60.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"100",
    "num":"100",
    "name":"Voltorb",
    "img":"https://pokegorealtime.com/static/images/pokedex/100.png",
    "type": "Electric",
    "height": "0.51 m",
    "weight": "10.4 kg",
    "candy": "50 Voltorb Candy",
    "egg": "5 km"
  },
  {
    "id":"101",
    "num":"101",
    "name":"Electrode",
    "img":"https://pokegorealtime.com/static/images/pokedex/101.png",
    "type": "Electric",
    "height": "1.19 m",
    "weight": "66.6 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"102",
    "num":"102",
    "name":"Exeggcute",
    "img":"https://pokegorealtime.com/static/images/pokedex/102.png",
    "type": "Grass / Psychic",
    "height": "0.41 m",
    "weight": "2.5 kg",
    "candy": "50 Exeggcute Candy",
    "egg": "5 km"
  },
  {
    "id":"103",
    "num":"103",
    "name":"Exeggutor",
    "img":"https://pokegorealtime.com/static/images/pokedex/103.png",
    "type": "Grass / Psychic",
    "height": "2.01 m",
    "weight": "120.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"104",
    "num":"104",
    "name":"Cubone",
    "img":"https://pokegorealtime.com/static/images/pokedex/104.png",
    "type": "Ground",
    "height": "0.41 m",
    "weight": "6.5 kg",
    "candy": "50 Cubone Candy",
    "egg": "5 km"
  },
  {
    "id":"105",
    "num":"105",
    "name":"Marowak",
    "img":"https://pokegorealtime.com/static/images/pokedex/105.png",
    "type": "Ground",
    "height": "0.99 m",
    "weight": "45.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"106",
    "num":"106",
    "name":"Hitmonlee",
    "img":"https://pokegorealtime.com/static/images/pokedex/106.png",
    "type": "Fighting",
    "height": "1.50 m",
    "weight": "49.8 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"107",
    "num":"107",
    "name":"Hitmonchan",
    "img":"https://pokegorealtime.com/static/images/pokedex/107.png",
    "type": "Fighting",
    "height": "1.40 m",
    "weight": "50.2 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"108",
    "num":"108",
    "name":"Lickitung",
    "img":"https://pokegorealtime.com/static/images/pokedex/108.png",
    "type": "Normal",
    "height": "1.19 m",
    "weight": "65.5 kg",
    "candy": "None",
    "egg": "5 km"
  },
  {
    "id":"109",
    "num":"109",
    "name":"Koffing",
    "img":"https://pokegorealtime.com/static/images/pokedex/109.png",
    "type": "Poison",
    "height": "0.61 m",
    "weight": "1.0 kg",
    "candy": "50 Koffing Candy",
    "egg": "5 km"
  },
  {
    "id":"110",
    "num":"110",
    "name":"Weezing",
    "img":"https://pokegorealtime.com/static/images/pokedex/110.png",
    "type": "Poison",
    "height": "1.19 m",
    "weight": "9.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"111",
    "num":"111",
    "name":"Rhyhorn",
    "img":"https://pokegorealtime.com/static/images/pokedex/111.png",
    "type": "Ground / Rock",
    "height": "0.99 m",
    "weight": "115.0 kg",
    "candy": "50 Rhyhorn Candy",
    "egg": "5 km"
  },
  {
    "id":"112",
    "num":"112",
    "name":"Rhydon",
    "img":"https://pokegorealtime.com/static/images/pokedex/112.png",
    "type": "Ground / Rock",
    "height": "1.91 m",
    "weight": "120.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"113",
    "num":"113",
    "name":"Chansey",
    "img":"https://pokegorealtime.com/static/images/pokedex/113.png",
    "type": "Normal",
    "height": "1.09 m",
    "weight": "34.6 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"114",
    "num":"114",
    "name":"Tangela",
    "img":"https://pokegorealtime.com/static/images/pokedex/114.png",
    "type": "Grass",
    "height": "0.99 m",
    "weight": "35.0 kg",
    "candy": "None",
    "egg": "5 km"
  },
  {
    "id":"115",
    "num":"115",
    "name":"Kangaskhan",
    "img":"https://pokegorealtime.com/static/images/pokedex/115.png",
    "type": "Normal",
    "height": "2.21 m",
    "weight": "80.0 kg",
    "candy": "None",
    "egg": "5 km"
  },
  {
    "id":"116",
    "num":"116",
    "name":"Horsea",
    "img":"https://pokegorealtime.com/static/images/pokedex/116.png",
    "type": "Water",
    "height": "0.41 m",
    "weight": "8.0 kg",
    "candy": "50 Horsea Candy",
    "egg": "5 km"
  },
  {
    "id":"117",
    "num":"117",
    "name":"Seadra",
    "img":"https://pokegorealtime.com/static/images/pokedex/117.png",
    "type": "Water",
    "height": "1.19 m",
    "weight": "25.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"118",
    "num":"118",
    "name":"Goldeen",
    "img":"https://pokegorealtime.com/static/images/pokedex/118.png",
    "type": "Water",
    "height": "0.61 m",
    "weight": "15.0 kg",
    "candy": "50 Goldeen Candy",
    "egg": "5 km"
  },
  {
    "id":"119",
    "num":"119",
    "name":"Seaking",
    "img":"https://pokegorealtime.com/static/images/pokedex/119.png",
    "type": "Water",
    "height": "1.30 m",
    "weight": "39.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"120",
    "num":"120",
    "name":"Staryu",
    "img":"https://pokegorealtime.com/static/images/pokedex/120.png",
    "type": "Water",
    "height": "0.79 m",
    "weight": "34.5 kg",
    "candy": "50 Staryu Candy",
    "egg": "5 km"
  },
  {
    "id":"121",
    "num":"121",
    "name":"Starmie",
    "img":"https://pokegorealtime.com/static/images/pokedex/121.png",
    "type": "Water / Psychic",
    "height": "1.09 m",
    "weight": "80.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"122",
    "num":"122",
    "name":"Mr. Mime",
    "img":"https://pokegorealtime.com/static/images/pokedex/122.png",
    "type": "Psychic",
    "height": "1.30 m",
    "weight": "54.5 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"123",
    "num":"123",
    "name":"Scyther",
    "img":"https://pokegorealtime.com/static/images/pokedex/123.png",
    "type": "Bug / Flying",
    "height": "1.50 m",
    "weight": "56.0 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"124",
    "num":"124",
    "name":"Jynx",
    "img":"https://pokegorealtime.com/static/images/pokedex/124.png",
    "type": "Ice / Psychic",
    "height": "1.40 m",
    "weight": "40.6 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"125",
    "num":"125",
    "name":"Electabuzz",
    "img":"https://pokegorealtime.com/static/images/pokedex/125.png",
    "type": "Electric",
    "height": "1.09 m",
    "weight": "30.0 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"126",
    "num":"126",
    "name":"Magmar",
    "img":"https://pokegorealtime.com/static/images/pokedex/126.png",
    "type": "Fire",
    "height": "1.30 m",
    "weight": "44.5 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"127",
    "num":"127",
    "name":"Pinsir",
    "img":"https://pokegorealtime.com/static/images/pokedex/127.png",
    "type": "Bug",
    "height": "1.50 m",
    "weight": "55.0 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"128",
    "num":"128",
    "name":"Tauros",
    "img":"https://pokegorealtime.com/static/images/pokedex/128.png",
    "type": "Normal",
    "height": "1.40 m",
    "weight": "88.4 kg",
    "candy": "None",
    "egg": "5 km"
  },
  {
    "id":"129",
    "num":"129",
    "name":"Magikarp",
    "img":"https://pokegorealtime.com/static/images/pokedex/129.png",
    "type": "Water",
    "height": "0.89 m",
    "weight": "10.0 kg",
    "candy": "400 Magikarp Candy",
    "egg": "2 km"
  },
  {
    "id":"130",
    "num":"130",
    "name":"Gyarados",
    "img":"https://pokegorealtime.com/static/images/pokedex/130.png",
    "type": "Water / Flying",
    "height": "6.50 m",
    "weight": "235.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"131",
    "num":"131",
    "name":"Lapras",
    "img":"https://pokegorealtime.com/static/images/pokedex/131.png",
    "type": "Water / Ice",
    "height": "2.49 m",
    "weight": "220.0 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"132",
    "num":"132",
    "name":"Ditto",
    "img":"https://pokegorealtime.com/static/images/pokedex/132.png",
    "type": "Normal",
    "height": "0.30 m",
    "weight": "4.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"133",
    "num":"133",
    "name":"Eevee",
    "img":"https://pokegorealtime.com/static/images/pokedex/133.png",
    "type": "Normal",
    "height": "0.30 m",
    "weight": "6.5 kg",
    "candy": "25 Eevee Candy (Evolution decided at random. Or, for first evolution, rename Eevee: Rainer => Vaporeon, Sparky => Jolteon, Pyro => Flareon)",
    "egg": "10 km"
  },
  {
    "id":"134",
    "num":"134",
    "name":"Vaporeon",
    "img":"https://pokegorealtime.com/static/images/pokedex/134.png",
    "type": "Water",
    "height": "0.99 m",
    "weight": "29.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"135",
    "num":"135",
    "name":"Jolteon",
    "img":"https://pokegorealtime.com/static/images/pokedex/135.png",
    "type": "Electric",
    "height": "0.79 m",
    "weight": "24.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"136",
    "num":"136",
    "name":"Flareon",
    "img":"https://pokegorealtime.com/static/images/pokedex/136.png",
    "type": "Fire",
    "height": "0.89 m",
    "weight": "25.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"137",
    "num":"137",
    "name":"Porygon",
    "img":"https://pokegorealtime.com/static/images/pokedex/137.png",
    "type": "Normal",
    "height": "0.79 m",
    "weight": "36.5 kg",
    "candy": "None",
    "egg": "5 km"
  },
  {
    "id":"138",
    "num":"138",
    "name":"Omanyte",
    "img":"https://pokegorealtime.com/static/images/pokedex/138.png",
    "type": "Rock / Water",
    "height": "0.41 m",
    "weight": "7.5 kg",
    "candy": "50 Omanyte Candy",
    "egg": "10 km"
  },
  {
    "id":"139",
    "num":"139",
    "name":"Omastar",
    "img":"https://pokegorealtime.com/static/images/pokedex/139.png",
    "type": "Rock / Water",
    "height": "0.99 m",
    "weight": "35.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"140",
    "num":"140",
    "name":"Kabuto",
    "img":"https://pokegorealtime.com/static/images/pokedex/140.png",
    "type": "Rock / Water",
    "height": "0.51 m",
    "weight": "11.5 kg",
    "candy": "50 Kabuto Candy",
    "egg": "10 km"
  },
  {
    "id":"141",
    "num":"141",
    "name":"Kabutops",
    "img":"https://pokegorealtime.com/static/images/pokedex/141.png",
    "type": "Rock / Water",
    "height": "1.30 m",
    "weight": "40.5 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"142",
    "num":"142",
    "name":"Aerodactyl",
    "img":"https://pokegorealtime.com/static/images/pokedex/142.png",
    "type": "Rock / Flying",
    "height": "1.80 m",
    "weight": "59.0 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"143",
    "num":"143",
    "name":"Snorlax",
    "img":"https://pokegorealtime.com/static/images/pokedex/143.png",
    "type": "Normal",
    "height": "2.11 m",
    "weight": "460.0 kg",
    "candy": "None",
    "egg": "10 km"
  },
  {
    "id":"144",
    "num":"144",
    "name":"Articuno",
    "img":"https://pokegorealtime.com/static/images/pokedex/144.png",
    "type": "Ice / Flying",
    "height": "1.70 m",
    "weight": "55.4 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"145",
    "num":"145",
    "name":"Zapdos",
    "img":"https://pokegorealtime.com/static/images/pokedex/145.png",
    "type": "Electric / Flying",
    "height": "1.60 m",
    "weight": "52.6 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"146",
    "num":"146",
    "name":"Moltres",
    "img":"https://pokegorealtime.com/static/images/pokedex/146.png",
    "type": "Fire / Flying",
    "height": "2.01 m",
    "weight": "60.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"147",
    "num":"147",
    "name":"Dratini",
    "img":"https://pokegorealtime.com/static/images/pokedex/147.png",
    "type": "Dragon",
    "height": "1.80 m",
    "weight": "3.3 kg",
    "candy": "25 Dratini Candy",
    "egg": "10 km"
  },
  {
    "id":"148",
    "num":"148",
    "name":"Dragonair",
    "img":"https://pokegorealtime.com/static/images/pokedex/148.png",
    "type": "Dragon",
    "height": "3.99 m",
    "weight": "16.5 kg",
    "candy": "100 Dratini Candy",
    "egg": "Not in Eggs"
  },
  {
    "id":"149",
    "num":"149",
    "name":"Dragonite",
    "img":"https://pokegorealtime.com/static/images/pokedex/149.png",
    "type": "Dragon / Flying",
    "height": "2.21 m",
    "weight": "210.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"150",
    "num":"150",
    "name":"Mewtwo",
    "img":"https://pokegorealtime.com/static/images/pokedex/150.png",
    "type": "Psychic",
    "height": "2.01 m",
    "weight": "122.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  },
  {
    "id":"151",
    "num":"151",
    "name":"Mew",
    "img":"https://pokegorealtime.com/static/images/pokedex/151.png",
    "type": "Psychic",
    "height": "0.41 m",
    "weight": "4.0 kg",
    "candy": "None",
    "egg": "Not in Eggs"
  }
];